// packages/react-mfe/src/MFE.tsx
import ReactDOM from 'react-dom/client';
import { App } from "./App";

export interface MFE {
    name: string,
    element: ReactDOM.Root;
    mount: (anchor: Element, data: any) => void;
    bootstrap: (anchor: Element, data: any) => void;
    destroy: () => void;
}

export const MFE = {
    name: 'reactMfe',
    element: document.createElement('reactRoot'),
    mount(anchor: Element, data: any) {
        const root = ReactDOM.createRoot(anchor);
        root.render(<App {...data} />);
    },
    bootstrap(anchor: Element, data: any) {
        this.mount(anchor, data);
    },
    destroy() {
        if (this.element) {
            if (this.element.parentNode) {
                this.element.parentNode.removeChild(this.element);
            }
        }
    },
};

// packages/lit-mfe/src/MFE.ts
import { html, render } from 'lit-html';
import { MyElement } from "./my-element";
import { RootPart } from 'lit';

export interface MFE {
    name: string,
    element: Element;
    mount: (anchor: Element, data: any) => void;
    bootstrap: (anchor: Element, data: any) => void;
    destroy: () => void;
}

export const MFE = {
    name: 'litMfe',
    rootElement: document.createElement('div'),
    mount(anchor: Element, data: any) {
        if (!customElements.get('my-element')) customElements.define('my-element', MyElement);
        const template = html`<my-element .data=${data}></my-element>`;
        anchor.appendChild(this.rootElement);
        render(template, this.rootElement);
    },
    bootstrap(anchor: Element, data: any) {
        if (!anchor.hasChildNodes()) this.mount(anchor, data);
    },
    destroy() {
        render(html``, this.rootElement);
        if (this.rootElement.parentNode) {
            this.rootElement.parentNode.removeChild(this.rootElement);
        }
    },
};
